name: EasyTier Docker Build (AMD64)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'EasyTier version to build (e.g. 2.4.1)'
        type: string
        required: true

env:
  DOCKERHUB_REPO: aoxijy/easytier-web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare artifacts
        run: |
          BUILD_VERSION="${{ github.event.inputs.version }}"
          echo "Building version: $BUILD_VERSION"
          URL="https://github.com/EasyTier/EasyTier/releases/download/v${BUILD_VERSION}/easytier-linux-x86_64-v${BUILD_VERSION}.zip"
          wget -O easytier.zip "$URL"
          unzip easytier.zip -d easytier-unpacked

          cd easytier-unpacked
          if [ -d "easytier-linux-x86_64" ]; then
            mv easytier-linux-x86_64 easytier-${BUILD_VERSION}
          fi
          cd easytier-${BUILD_VERSION}

          chmod +x easytier-core
          chmod +x easytier-web-embed

          mkdir -p docker-context
          
          # 复制应用程序文件
          cp easytier-core docker-context/
          cp easytier-web-embed docker-context/
          
          # 复制Web资源
          if [ -d "web" ]; then
            cp -r web docker-context/
          else
            echo "警告：未找到web目录，Web界面可能无法正常工作"
            mkdir -p docker-context/web
          fi
          
          # 返回仓库根目录复制 start.sh
          cd ../..
          cp start.sh easytier-unpacked/easytier-${BUILD_VERSION}/docker-context/

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./easytier-unpacked/easytier-${{ github.event.inputs.version }}/docker-context
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ github.event.inputs.version }}
            ${{ env.DOCKERHUB_REPO }}:latest
