name: EasyTier Docker Build (AMD64)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      version:
        description: 'EasyTier version to build (e.g. 2.4.1)'
        type: string
        default: 'latest'
        required: false

env:
  DOCKERHUB_REPO: aoxijy/easytier-web

jobs:
  version-check:

  build:
    needs: version-check
    if: ${{ needs.version-check.outputs.should_build == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Prepare artifacts
        run: |
          BUILD_VERSION=${{ needs.version-check.outputs.build_version }}
          echo "Building version: $BUILD_VERSION"
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
          
          # 下载官方 Release 压缩包
          URL="https://github.com/EasyTier/EasyTier/releases/download/v${BUILD_VERSION}/easytier-linux-x86_64-v${BUILD_VERSION}.zip"
          wget -O easytier.zip "$URL"
          
          # 解压ZIP文件
          unzip easytier.zip -d easytier-unpacked
          
          # 修复目录路径：使用实际解压目录
          cd "easytier-unpacked/easytier-linux-x86_64"
          
          # 确保可执行权限
          chmod +x easytier-core
          
          # 构建Web界面
          if [ -f "easytier-web-embed" ]; then
            chmod +x easytier-web-embed
            ./easytier-web-embed --build-web
          fi
          
          # 创建Docker构建上下文
          mkdir -p docker-context
          cp easytier-core docker-context/
          
          # 复制Web资源
          if [ -d "web" ]; then
            cp -r web docker-context/web
          fi
          
          # 复制Dockerfile到构建上下文
          cp ../../../Dockerfile docker-context/
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./easytier-unpacked/easytier-linux-x86_64/docker-context
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.BUILD_VERSION }}
            ${{ env.DOCKERHUB_REPO }}:latest
      
      - name: Send success notification
        if: success()
        run: |
          echo "✅ Successfully built and pushed ${{ env.DOCKERHUB_REPO }}:${{ env.BUILD_VERSION }}"
