name: EasyTier Docker Build (AMD64)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'EasyTier version to build (e.g. 2.4.2)'
        type: string
        required: true

env:
  DOCKERHUB_REPO: aoxijy/easytier-web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare artifacts
        run: |
          BUILD_VERSION="${{ github.event.inputs.version }}"
          echo "Building version: $BUILD_VERSION"
          URL="https://github.com/EasyTier/EasyTier/releases/download/v${BUILD_VERSION}/easytier-linux-x86_64-v${BUILD_VERSION}.zip"
          wget -O easytier.zip "$URL"
          unzip easytier.zip -d easytier-unpacked

          cd easytier-unpacked
          if [ -d "easytier-linux-x86_64" ]; then
            mv easytier-linux-x86_64 easytier-${BUILD_VERSION}
          fi
          cd easytier-${BUILD_VERSION}

          chmod +x easytier-core
          chmod +x easytier-web-embed

          mkdir -p docker-context
          
          # 复制应用程序文件
          cp easytier-core docker-context/
          cp easytier-web-embed docker-context/
          
          # 复制Web资源
          if [ -d "web" ]; then
            cp -r web docker-context/
          else
            echo "警告：未找到web目录，Web界面可能无法正常工作"
            mkdir -p docker-context/web
          fi
          
          # 生成新的启动脚本 start.sh
          echo '#!/bin/sh' > docker-context/start.sh
          echo 'set -e' >> docker-context/start.sh
          echo '' >> docker-context/start.sh
          echo '# 设置默认值' >> docker-context/start.sh
          echo 'CORE_PORT=${ET_CORE_PORT:-11010}' >> docker-context/start.sh
          echo 'WEB_PORT=${ET_WEB_PORT:-8080}' >> docker-context/start.sh
          echo 'NETWORK_NAME=${ET_NETWORK_NAME:-default}' >> docker-context/start.sh
          echo 'NETWORK_SECRET=${ET_NETWORK_SECRET:-}' >> docker-context/start.sh
          echo '' >> docker-context/start.sh
          echo '# API主机配置' >> docker-context/start.sh
          echo 'if [ -n "$ET_API_HOST" ]; then' >> docker-context/start.sh
          echo '  API_HOST="$ET_API_HOST"' >> docker-context/start.sh
          echo 'else' >> docker-context/start.sh
          echo '  API_HOST="http://localhost:$CORE_PORT"' >> docker-context/start.sh
          echo 'fi' >> docker-context/start.sh
          echo '' >> docker-context/start.sh
          echo '# 启动核心服务' >> docker-context/start.sh
          echo 'echo "启动 easytier-core..."' >> docker-context/start.sh
          echo '/usr/local/bin/easytier-core \' >> docker-context/start.sh
          echo '  --rpc-portal "0.0.0.0:$CORE_PORT" \' >> docker-context/start.sh
          echo '  --vpn-portal "0.0.0.0:$CORE_PORT" \' >> docker-context/start.sh
          echo '  --network-name "$NETWORK_NAME" \' >> docker-context/start.sh
          echo '  ${NETWORK_SECRET:+--network-secret "$NETWORK_SECRET"} \' >> docker-context/start.sh
          echo '  --listeners "tcp:$CORE_PORT" \' >> docker-context/start.sh
          echo '  --listeners "udp:$CORE_PORT" \' >> docker-context/start.sh
          echo '  --listeners "wg:11011" &' >> docker-context/start.sh
          echo '' >> docker-context/start.sh
          echo '# 启动Web服务' >> docker-context/start.sh
          echo 'echo "启动 easytier-web-embed..."' >> docker-context/start.sh
          echo '/usr/local/bin/easytier-web-embed \' >> docker-context/start.sh
          echo '  --web-server-port "$WEB_PORT" \' >> docker-context/start.sh
          echo '  --api-host "$API_HOST" &' >> docker-context/start.sh
          echo '' >> docker-context/start.sh
          echo '# 等待所有服务' >> docker-context/start.sh
          echo 'wait' >> docker-context/start.sh
          
          # 设置可执行权限
          chmod +x docker-context/start.sh
          
          # 列出构建上下文内容
          echo "构建上下文内容："
          ls -l docker-context

          cd ../..
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./easytier-unpacked/easytier-${{ github.event.inputs.version }}/docker-context
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ github.event.inputs.version }}
            ${{ env.DOCKERHUB_REPO }}:latest
            
      - name: Test Docker image
        run: |
          # 测试镜像基本功能
          docker run --rm ${{ env.DOCKERHUB_REPO }}:${{ github.event.inputs.version }} /usr/local/bin/easytier-core --version
          docker run --rm ${{ env.DOCKERHUB_REPO }}:${{ github.event.inputs.version }} /usr/local/bin/easytier-web-embed --version
          
          # 测试启动脚本
          docker run --rm ${{ env.DOCKERHUB_REPO }}:${{ github.event.inputs.version }} cat /usr/local/bin/start.sh
          
          # 测试核心参数是否有效
          docker run --rm -e ET_NETWORK_NAME=test_network ${{ env.DOCKERHUB_REPO }}:${{ github.event.inputs.version }} \
            /usr/local/bin/easytier-core --help | grep -- '--network-name'
