#!/bin/sh

# 设置日志级别 (可根据需要调整)
LOG_LEVEL=${LOG_LEVEL:-info}

# 启动easytier-web-embed服务
/usr/local/bin/easytier-web-embed \
  --db /data/et.db \
  --console-log-level $LOG_LEVEL \
  --file-log-level $LOG_LEVEL \
  --file-log-dir /var/log/easytier \
  --config-server-port 22020 \
  --config-server-protocol udp \
  --api-server-port 11211 \
  --web-server-port 8080 \
  &
WEB_PID=$!

# 启动easytier-core服务
/usr/local/bin/easytier-core &
CORE_PID=$!

# 捕获退出信号
cleanup() {
  echo "终止服务..."
  kill $WEB_PID
  kill $CORE_PID
  wait
  exit 0
}

trap cleanup TERM INT

# 等待子进程退出
wait $WEB_PID $CORE_PID
cleanup
