name: Build and Publish EasyTier Docker Image

on:
  push:
    branches:
      - main  # 当推送到主分支时自动触发构建
  workflow_dispatch:  # 支持手动触发构建

env:
  DOCKERHUB_REPO: aoxijy/easytier-web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout 仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker Hub 登录
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 下载并解压 EasyTier Release
      - name: Download and extract EasyTier release
        run: |
          # 获取版本号（默认为最新版本）
          BUILD_VERSION="${{ github.sha }}"  # 使用 Git SHA 作为版本，或者你可以指定具体版本号
          
          # 下载并解压 EasyTier 版本包
          URL="https://github.com/EasyTier/EasyTier/releases/download/v${BUILD_VERSION}/easytier-linux-x86_64-v${BUILD_VERSION}.zip"
          wget -O easytier.zip "$URL"
          unzip easytier.zip -d easytier-unpacked
          cd easytier-unpacked/easytier-linux-x86_64
          
          # 确保 `easytier-core` 和 `easytier-web-embed` 文件有执行权限
          chmod +x easytier-core
          chmod +x easytier-web-embed

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKERHUB_REPO }}:${{ github.sha }} -f Dockerfile .
          docker tag ${{ env.DOCKERHUB_REPO }}:${{ github.sha }} ${{ env.DOCKERHUB_REPO }}:latest

      # 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKERHUB_REPO }}:${{ github.sha }}
          docker push ${{ env.DOCKERHUB_REPO }}:latest

      # 发送成功通知
      - name: Send success notification
        if: success()
        run: echo "✅ Docker image successfully built and pushed to Docker Hub!"
